import path from "path";
import { parseArgs } from "util";
import { z } from "zod";
import fs from "node:fs";
import { fileURLToPath } from "url";
import { dirname } from "path";
import { zodToJsonSchema } from "zod-to-json-schema";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const topicsDir = path.join(__dirname, "./metadata/topics");
const languagesDir = path.join(__dirname, "./metadata/languages");

const validTopics = fs.readdirSync(topicsDir).map(f => f.replace(".yaml", ""));
const validLanguages = fs.readdirSync(languagesDir).map(f => f.replace(".yaml", ""));

const allValidTags = [...validTopics, ...validLanguages];

if (allValidTags.length === 0) {
    throw new Error("No metadata entities found!");
}

const EntityTagEnum = z.enum([
    allValidTags[0],
    ...allValidTags.slice(1),
] as [string, ...string[]]);

/**
 * Pricing schema
 */
const PricingSchema = z.union([
    z.object({
        model: z.enum(["Free", "Freemium"]).describe(
            "Free(mium) pricing model."
        ),
    }).strict(),

    z.object({
        model: z.enum(["Subscription", "One Time"]).describe(
            "Paid pricing model."
        ),
        amount: z.number().gt(0).describe("Price in USD"),
    }).strict(),
]);

export const LanguageDomainSchema = z.enum([
    "Web Development",
    "Data Science",
    "Mobile Development",
    "Game Development",
    "Systems Programming",
    "Scripting",
    "General Purpose",
    "DevOps",
]);

export const ProgrammingParadigmSchema = z.enum([
    "Object-Oriented Programming",
    "Functional Programming",
    "Procedural Programming",
    "Logic Programming",
]);

export const ResourceCategorySchema = z.discriminatedUnion("type", [
    z.object({
        type: z.literal("Language"),
        paradigms: z.array(ProgrammingParadigmSchema),
    }),
    z.object({
        type: z.literal("Platform"),
    }),
    z.object({
        type: z.literal("Tool"),
    }),
]);

const ResourceTypeSchema = z.enum([
    "Video",
    "Article",
    "Interactive Tutorial",
    "Book",
    "Course",
]);

export const ResourceSchema = z.object({
    name: z.string(),
    description: z.string().max(256).optional(),
    url: z.string().url(),
    type: z.array(ResourceTypeSchema).min(1),
    teaches: z.array(EntityTagEnum).min(1),
    pricing: PricingSchema,
    pros: z.array(z.string()).optional(),
    cons: z.array(z.string()).optional(),
}).strict();

export const MetaSchema = z.object({
    name: z.string(),
    description: z.string(),
    emoji: z.string().optional(),
    domains: z.array(LanguageDomainSchema),
    category: ResourceCategorySchema,
}).strict();

export const CompiledMetaSchema = MetaSchema.extend({
    id: z.string(),
}).strict();

export const DatabaseSchema = z.object({
    metadata: z.array(CompiledMetaSchema),
    resources: z.array(ResourceSchema),
}).strict();

export type Meta = z.infer<typeof MetaSchema>;
export type Resource = z.infer<typeof ResourceSchema>;
export type Database = z.infer<typeof DatabaseSchema>;

function main() {
    const header = "// Generated by index.ts - DO NOT EDIT THIS FILE DIRECTLY";

    const { values } = parseArgs({
        args: process.argv,
        options: {
            schema: { type: "string" },
        },
        strict: true,
        allowPositionals: true,
    });

    let schema: z.ZodTypeAny;

    switch (values.schema?.toLowerCase()) {
        case "metadata":
            schema = MetaSchema;
            break;
        case "resource":
            schema = ResourceSchema;
            break;
        case "database":
            schema = DatabaseSchema;
            break;
        case undefined:
            console.error(
                "No schema specified. Use --schema (metadata | resource | database)"
            );
            process.exit(1);
        default:
            console.error(`Unknown schema: ${values.schema}`);
            process.exit(1);
    }

    console.log(header);
    console.log(JSON.stringify(zodToJsonSchema(schema), null, 2));
}

if (import.meta.main) {
    main();
}
