FROM openjdk:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/learning-webservice-0.0.1-SNAPSHOT-standalone.jar /learning-webservice/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/learning-webservice/app.jar"]
