name: Validate YAMLs against JSON Schema

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


permissions:
  contents: read
  pull-requests: write # enable write permissions for pull request comments


jobs:
  verify-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate JSON
        uses: GrantBirki/json-yaml-validate@v1.4.0
        with:
          base_dir: resources
          comment: "true" # enable comment mode