# Validates all the YAML files against the JSON schema

name: Validate YAMLs against JSON Schema

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write # enable write permissions for pull request comments

jobs:
  verify-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate JSON
        uses: GrantBirki/json-yaml-validate@v1.5.0
        with:
          base_dir: resources
          json_schema: "resource.schema.json"
          yaml_as_json: "true" # enable YAML to JSON conversion
          comment: "true" # enable comment mode
